### ISSUE TITLE
Strange error on parameter output

### ISSUE THREAD

**Issue by dantaeyoung** [MahmoudAbdelRahman/GH_CPython#16]
I'm getting a strange error when returning a very specific value: "Line(3)" as an output.

My code is:
```
s = "Line(0123456789)"
output_ = s
```
![screenshot](http://imgur.com/91ZsA2H.jpg)

Any ideas? Thank you, @MahmoudAbdelRahman !

**Comment by MahmoudAbdelRahman** [comment]
Hi @dantaeyoung, 
Thanks so much for the feedback, 
Yes, this problem occurs because I'm now trying to add Grasshopper library. so if you set the output to be for example `output_ = "Line(ax, ay, az, bx, by, bz)"` it will add a new line with these parameters. 
#### I've changed this code a little bit to be as follows:
 `output_ = "gCPy.Line(ax, ay, az, bx, by, bz)"`, I don't know if it is a good practice or not, but I'll try to make it as good as possible. 
![image](https://user-images.githubusercontent.com/6969514/29491797-f0b67b76-8566-11e7-9c6a-e9d82d625a94.png)

The next update should include Grasshopper module, for example, to add new line it will be as follows (it is still under development):
```Python
import Grasshopper as gh
output = gh.addLine(0., 0., 0., 5., 5., 0.)
#or
p1 = gh.Point3(0., 0., 0.)
p2 = gh.Point3(5., 5., 0)

output_ = gh.addLine(p1, p2)

```
**any suggestions or comments or feedback are most welcome.** 
Thanks so much. 
Best regards, 
Mahmoud Abdelrahman.

**Comment by MahmoudAbdelRahman** [comment]
Hi @dantaeyoung , 
You can download the modified version [from here](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip), You will notice a new file called `Grasshopper.py` at `C:\GH_CPython\`. 

**This is example of what it could do**

![image](https://user-images.githubusercontent.com/6969514/29546917-4360cd9a-86f7-11e7-9e45-8b3c06487bfb.png)

Sincere regards
**Mahmoud AbdelRahman**

**Comment by dantaeyoung** [comment]
Thanks for this @MahmoudAbdelRahman !

Question/suggestion: would it be better/easier to implement [Rhinoscriptsyntax](https://github.com/mcneel/rhinoscriptsyntax)? That way it's guaranteed that GH_CPython gh implementation can follow that of GH_Python, rather than having to recreate all GH functions and potentially introducing a layer of bugs/maintenance..

**Comment by MahmoudAbdelRahman** [comment]
Hi @dantaeyoung , 
Yes, I totally agree with you, I'm trying to find a way to do this. 
Thanks so much.
