### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by SpencerMAQ** [MahmoudAbdelRahman/GH_CPython#19]
Hi Mahmoud,

I have some problems with the component, I did as instructed in the wiki; placing the `.gha` and the `.dll` inside `./Libraries`. I also ran Rhino as admin. The component appears on my component tab but it won't run anything. Also, File>Open and Save as doesn't open a window.

Clicking test only updates the 'successful in _ ...' part.

I've tried `Py 2.7, 3.5 and 3.6`. Could you help me? Thanks in advance!
![2](https://user-images.githubusercontent.com/25006084/29823891-95ae0296-8d02-11e7-9ff2-57fab21e50b5.JPG)

Btw, I was also wondering what the little green box was for.
Looks like this is going to be my new favorite plugin :)

**Comment by MahmoudAbdelRahman** [comment]
@SpencerMAQ 
Hi Micheal, 
Thanks so much for your feedback, I'm trying to figure out what is the problem?
 
- Would you please check if a new folder in the `C:\` partition called `C:\GH_CPython\` has been created? 
- May be the problem is that it is not the [latest update of the plugin](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip) ? 
- When you change the python version , and reopen the `locatePython` window, does the interpreter remain as you have set?
----

Yes, you are right 👍 , `File > open` and `save` haven't been activated yet, I'll start working on them now. :) . but `Data>manage data> inputs` is working now. 
----
The green box was supposed to work as a led light. but I forgot about it, I'll modify it as soon as possible.

Thanks so much for your words, I hope that it works well. I'll be in touch until the problem is solved. and I look forward your feedback. 

![image](https://user-images.githubusercontent.com/6969514/29827651-d0aa7dfc-8cda-11e7-83e8-fe1bfe431c25.png)


Regards, 
Mahmoud Abdelrahman

**Comment by SpencerMAQ** [comment]
Thanks for the quick reply.

Yes, it did create the folder on `C:\`.

I reinstalled from the [link](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip) to ensure that I have the latest version but it still won't work.

Yes, the interpreter was saved
![3](https://user-images.githubusercontent.com/25006084/29828277-d7668c56-8d0e-11e7-82f9-682a31d922c2.JPG)

I'm off to sleep for now, I'll try to install the plugin on a different computer tomorrow to check if it's this computer that's buggy.

Regards,
Spencer

**Comment by MahmoudAbdelRahman** [comment]
Hi Spencer, 

I think I have solved this problem, would you please try it ? 
https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip

Thanks so much. 
Regards, 
Mahmoud

**Comment by SpencerMAQ** [comment]
Indeed, it fix fix the problem. Thanks you.
I had to plug in something into the input though before the component ran but I guess this is a minor issue. 

![screenshot 3](https://user-images.githubusercontent.com/25006084/29858709-4ad3e756-8d91-11e7-967b-56c765a42771.png)
One last thing. I tried installing it on my laptop and this appeared. It's not much of a problem since I don't use my laptop very much but I though I'd let you know just in case.

Regards,
Spencer

**Comment by MahmoudAbdelRahman** [comment]
Hi Spencer,
This is great!. Thanks so much.
Have you copied the file : `FastColoredTextBox.dll` into Grasshopper libraries' folder on your labtop?

Regards, 
Mahmoud

**Comment by SpencerMAQ** [comment]
Yes, both the `dll` and `gha` were copied. I also ran it as admin.

Regards,
Spencer

**Comment by yudaiAAA** [comment]
Hi Mahmoud, Spencer
I am a student majoring Architecture. 
I have same problem about this
![capture](https://user-images.githubusercontent.com/34510874/40275505-90a75312-5c2b-11e8-96f6-a16a0f09469b.PNG)

My laptop have Python 3.6 and 2.7
I have already installed dll and gha files into libraries' folder 

Could you give me some advise??

thank you
Regards
Yudai

**Comment by dantaeyoung** [comment]
@yudaiAAA @SpencerMAQ Have you all [unblocked the DLL](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/)?
